http:
  routers:
    api:
      rule: Host(`api.kanellos.me`)
      service: api-backend
  services:
    api-backend:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:5000
